name: capstone
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - plotly
  - prophet
  - xgboost
  - tensorflow
  - keras-preprocessing
  - pytorch
  - streamlit
